# Generated by Django 6.0.5 on 2026-08-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_transaction_finances_tr_user_id_5d91a0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=10),
        ),
    ]
